#!/bin/python3
"""
Problem: Calculate and print the sum of the elements in an array, keeping in mind that some of those integers may be quite large.

For example, an input of: 
5 (Size of the array)
1000000001 1000000002 1000000003 1000000004 1000000005 (Actual elements in the array)

would return:
5000000015
"""

import math
import os
import random
import re
import sys

# Complete the aVeryBigSum function below.
# Author: Mehdi Naderi Varandi

def aVeryBigSum(ar):
    answer=0

    for i in ar: #Go through array one by one and increment answer with i
        answer+=i

    return (answer)

    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = aVeryBigSum(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
