#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
# Author: 

def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Arguments are as follows ------------------------
    
    #   s is the left most point of Sam's house
    #   t is the right most point of Sam's house
    #   Hence, Sam's house is between s - t

    #   a is location of Apple tree
    #   b is location of Orange tree
    
    # --------------------------------------------------
    
    
    appleLocations=[]
    orangeLocations=[]

    appleCounter=0
    orangeCounter=0
    
    
    #Part of code that calculates distances between house and the trees
    for i in apples:
        appleLocations.append(a + i)

    for i in oranges:
        orangeLocations.append(b + i)


    for i in appleLocations:
        if (i>=s) and (i<=t):
            appleCounter+=1

    for i in orangeLocations:
        if (i>=s) and (i<=t):
            orangeCounter+=1
    #-------------------------------------------------------------------
            
            
    #Output answer
    print (appleCounter)
    print (orangeCounter)




if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
