#!/bin/python3

import math
import os
import random
import re
import sys

"""
You are in charge of the cake for your niece's birthday and have decided the cake will have one candle for each year of her total age.
When she blows out the candles, she’ll only be able to blow out the tallest ones. 
Your task is to find out how many candles she can successfully blow out.

For example, if your niece is turning 4 years old, and the cake will have 4 candles of height 4, 4, 1, 3, 
she will be able to blow out 2 candles successfully, since the tallest candles are of height 4 and there are 2 such candles. 

"""


#Answer submission starts here --------------
# Complete the birthdayCakeCandles function below.
def birthdayCakeCandles(ar):
    tallest=max(ar) #Finds the biggest integer in the array and holds it at the variable 'tallest'
    counter=0       #Variable counter that checks the number of times 

    for i in ar:   
        if (i==tallest): #Checks if i is equal to the biggest candle/item 
            counter+=1   #If so, increment the counter

    return (counter)

#End of submission ---------------------------




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
