#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the birthdayCakeCandles function below.
def birthdayCakeCandles(ar):
    tallest=max(ar) #Finds the biggest integer in the array and holds it at the variable 'tallest'
    counter=0       #Variable counter that checks the number of times 

    for i in ar:   
        if (i==tallest):
            counter+=1

    return (counter)






if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
