#!/bin/python3

import os
import sys

"""
Problem: HackerLand University has the following grading policy:

Every student receives a grade in the inclusive range from 0 to 100.
Any less than 40 is a failing grade.

Sam is a professor at the university and likes to round each student's grade according to these rules:

If the difference between the grade and the next multiple of is less than 3, round up to the next multiple of 5.
If the value of grade is less than 38, no rounding occurs as the result will still be a failing grade.

For example, (grade = 84) will be rounded to (85) but (grade = 29) will not be rounded because the rounding would result in a number that is less than (40).

Given the initial value of grade for each of Sam's n students, write code to automate the rounding process. 
"""



# Beginning of submission ---------------------------------------------
# Complete the gradingStudents function below.
# Author: Mehdi Naderi Varandi

def gradingStudents(grades):
    roundingMargin=3 #holds the rounding margin e.g. if the next multiple is less than 3/roundingMargin
    answer=[]        #array for holding the answers and returning them later

    for i in grades:
        
        if (i>37):
            nextMultiple=round(i*2,-1)/2  #Conversion process to get the next multiple of 5
            nextMultiple=int(nextMultiple) #holds the next multiple of 5

            if ((nextMultiple-i)<=3) and ((nextMultiple-i)>0): #Compares i with the next multiple of 5, and sees whether...
                #...save the rounded up version or not
                
                answer.append(nextMultiple)
            else:
                answer.append(i)

        else:
            answer.append(i)
        
    return(answer)

# End of submission -----------------------------------------------------


if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    grades = []

    for _ in range(n):
        grades_item = int(input())
        grades.append(grades_item)

    result = gradingStudents(grades)

    f.write('\n'.join(map(str, result)))
    f.write('\n')

    f.close()
