#!/bin/python3

import math
import os
import random
import re
import sys

"""
Problem: 

You are choreographing a circus show with various animals. 

For one act, you are given two kangaroos on a number line ready to jump in the positive direction (i.e, toward positive infinity).

    1) The first kangaroo starts at location x1 and moves at a rate of v1 meters per jump.
    
    2) The second kangaroo starts at location x2 and moves at a rate of v2 meters per jump.

You have to figure out a way to get both kangaroos at the same location at the same time as part of the show. 
If it is possible, return YES, otherwise return NO.

For example, kangaroo 1 starts at x1 = 2 with a jump distance v1 = 1 and kangaroo 2 starts at x2 = 1 with a jump distance of v2 = 2. 
After one jump, they are both at x = 3, (x1 + v1 = 2 + 1, x2 + v2 = 1 + 2), so our answer is YES.

Constraints:
    1) 0 <= x1 < x2 <= 10000
    2) 1 <= v1 <= 10000
    3) 1 <= v2 <= 10000

"""

# Complete the kangaroo function below.

# Solution for this problem is as follows
# Author: Mehdi Naderi Varandi
def kangaroo(x1, v1, x2, v2):
    # x1, v1: integers, starting position and jump distance for kangaroo 1
    # x2, v2: integers, starting position and jump distance for kangaroo 2
    
    
    for i in range(0,10000): #Simplest solution to write is literally just to loop through 0 to 1000
        #This is because the constraints are between e.g. (0 or 1) to 10,000 for x1/x2/v1/v2
        
        if (x1==x2): #Checks whether the position of both kangaroo 1 and 2 are equal
            return ("YES") #If so, then just return YES

        x1+= v1 #Moves the position of kangaroo 1 by v1 meteres
        x2+= v2 #Moves the position of kangaroo 2 by v2 meteres

    return "NO" #If this point is reached, then that means that the loop wasn't able to find a time where the...
    #positions of kangaroo 1 and 2 were equal. In this scenario, the function just returns NO instead




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
