#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the migratoryBirds function below.
def migratoryBirds(arr):
    #There's only 5 types of birds expected
    typeOne=0
    typeTwo=0
    typeThree=0
    typeFour=0
    typeFive=0

    for i in arr:
        if (i==1):
            typeOne+=1
        elif (i==2):
            typeTwo+=1
        elif (i==3):
            typeThree+=1
        elif (i==4):
            typeFour+=1
        else:
            typeFive+=1

    answer=[]
    answer.append(typeOne)
    answer.append(typeTwo)
    answer.append(typeThree)
    answer.append(typeFour)
    answer.append(typeFive)

    loopCounter=0

    for i in answer:
        loopCounter+=1
        
        if (i==(max(answer))):
            return (loopCounter)



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
