#!/bin/python3

import math
import os
import random
import re
import sys
"""
Problem: 

You have been asked to help study the population of birds migrating across the continent. 

Each type of bird you are interested in will be identified by an integer value. 
Each time a particular kind of bird is spotted, its id number will be added to your array of sightings. 
You would like to be able to find out which type of bird is most common given a list of sightings. 

Your task is to print the type number of that bird and if two or more types of birds are equally common, 
choose the type with the smallest ID number.

For example, assume your bird sightings are of types arr = [1,1,2,2,3]. 
There are two each of types 1 and 2, and one sighting of type 3. Pick the lower of the two types seen twice: type 1. 
"""


# Complete the migratoryBirds function below.
# Author: Mehdi Naderi Varandi

def migratoryBirds(arr):
    #There's only 5 types of birds expected
    typeOne=0
    typeTwo=0
    typeThree=0
    typeFour=0
    typeFive=0

    for i in arr:
        if (i==1):
            typeOne+=1
        elif (i==2):
            typeTwo+=1
        elif (i==3):
            typeThree+=1
        elif (i==4):
            typeFour+=1
        else:
            typeFive+=1

    answer=[]
    answer.append(typeOne)
    answer.append(typeTwo)
    answer.append(typeThree)
    answer.append(typeFour)
    answer.append(typeFive)

    loopCounter=0

    for i in answer:
        loopCounter+=1
        
        if (i==(max(answer))):
            return (loopCounter)



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
