#!/bin/python3
"""
Problem:

Consider a staircase of size (n=4):

   #
  ##
 ###
####

Observe that its base and height are both equal to n and the image is drawn using # symbols and spaces. 
The last line is not preceded by any spaces.

Write a program that prints a staircase of size n
"""

import math
import os
import random
import re
import sys

# Complete the staircase function below.
# Solution for the Staircase problem
# Author: Mehdi Naderi Varandi
def staircase(n):
    
    
    stringOutput="#" #String variable used later on to output the # character 
    spaceCharacters=" "
    spacePosition=1

    stringOutput=((spaceCharacters*(n-spacePosition)) + "#")

    initialCharacter="#"

    stringHorziontal=2
    spacePosition+=1

    for i in range(1,n): #Goes from each level to N e.g. from 1 to 5 (maximum level)
    
        stringOutput += ("\n" + (spaceCharacters*(n-spacePosition))+ (stringHorziontal*initialCharacter))
        #Outputs line/# elements equal to the relevant number needed at that specific position
      
        stringHorziontal+=1
        spacePosition+=1

    print(stringOutput) #Return answer
   
#End of submission





if __name__ == '__main__':
    n = int(input())

    staircase(n)
