#!/bin/python3
"""
Problem:

Consider a staircase of size (n=4):

   #
  ##
 ###
####

Observe that its base and height are both equal to n and the image is drawn using # symbols and spaces. 
The last line is not preceded by any spaces.

Write a program that prints a staircase of size n
"""

import math
import os
import random
import re
import sys

# Complete the staircase function below.
# Solution for the Staircase problem
# Author: Mehdi Naderi Varandi
def staircase(n):
    
    
    stringOutput="#"
    spaceCharacters=" "
    spacePosition=1

    stringOutput=((spaceCharacters*(n-spacePosition)) + "#")

    initialCharacter="#"

    stringHorziontal=2
    spacePosition+=1

    for i in range(1,n):
    
        stringOutput += ("\n" + (spaceCharacters*(n-spacePosition))+ (stringHorziontal*initialCharacter))

        stringHorziontal+=1
        spacePosition+=1

    print(stringOutput)






if __name__ == '__main__':
    n = int(input())

    staircase(n)
